### ISSUE TITLE
I tried to run it and ran into some problems

### ISSUE THREAD

**Issue by binglebai** [JaidedAI/JaidedRead#3]
Warning error
`Traceback (most recent call last):
  File "C:/Users/amp/PycharmProjects/untitled3/test.py", line 2, in <module>
    reader = jaidedread.Reader(['th','en'])
  File "C:\Users\amp\PycharmProjects\untitled3\venv\lib\site-packages\jaidedread\jaidedread.py", line 87, in __init__
    char_list =  input_file.read().splitlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 2: illegal multibyte sequence
`
I don't know what to do about it

**Comment by rkcosmos** [comment]
I think it has to do with file decoding which was fixed by @wannaphong in the last merge (by adding encoding = "utf-8-sig"). Can you try download the last version

pip install git+git://github.com/jaidedai/jaidedread.git

 and try again?

**Comment by binglebai** [comment]
How much gpu memory is needed to run this program? Can i change bath_size because my computer only have  2 GiB

**Comment by rkcosmos** [comment]
Default batch_size is already minimum. It consumed 2.xx GiB on my computer. You can try to run on cpu mode by adding optional argument.

 reader = jaidedread.Reader(['en'], gpu = False)

**Comment by binglebai** [comment]
i try to run on cpu mode  but  have new problem
`RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

**Comment by rkcosmos** [comment]
Code is not tested on Windows yet. I'll fix it in next update.

**Comment by binglebai** [comment]
Looking forward to the next update

**Comment by rkcosmos** [comment]
I just tried it on windows. What you need is [(https://stackoverflow.com/questions/24363300/freeze-support-bug-in-using-scikit-learn-in-the-anaconda-python-distro)]. You need to wrap everything in main() and call it.

for example, in your yourfilename.py 

import jaidedread

def main():
    read=jaidedread.Reader(['en'], gpu=False)
    text =read.readtext('covid.jpg', workers=1, batch_size=1)
    print(text)
    
if __name__ == '__main__':
    main()

**Comment by binglebai** [comment]
It's working fine
Can you share some information about this?
Or a tutorial?
I am a college student just beginning to study deep learning

**Comment by rkcosmos** [comment]
I recommend reading those links in 'Acknowledgement and References' Section.

**Comment by binglebai** [comment]
thanks
